# Generated by Django 3.0.1 on 2020-02-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumia', '0007_electronicsscrape_fashionscrape'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthBeautyScrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('product', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10)),
                ('old_price', models.CharField(max_length=10)),
                ('product_url', models.URLField(max_length=300, unique=True)),
                ('img_url', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='KidsFashionScrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('product', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10)),
                ('old_price', models.CharField(max_length=10)),
                ('product_url', models.URLField(max_length=300, unique=True)),
                ('img_url', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MenFashionScrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('product', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10)),
                ('old_price', models.CharField(max_length=10)),
                ('product_url', models.URLField(max_length=300, unique=True)),
                ('img_url', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='WomenFashionScrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('product', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10)),
                ('old_price', models.CharField(max_length=10)),
                ('product_url', models.URLField(max_length=300, unique=True)),
                ('img_url', models.URLField(max_length=300)),
            ],
        ),
    ]
